[DEFAULT]
partition          = shared
mem                = 30G
ntasks             = 1
time               = 0:05:00
xpid               = reanalysis_era5.8_crocus3.0.2_std
namelist_source    = OPTIONS_V9_reanalysis.nam
uenv               = uenv:surfex_reanalysis_2026@vernaym
test               = True

# Actual PREP file for entire reanalysis run
#prep_xpid          = spinup_crocus3.0.2_std
#prep_user          = lafaysse

# PREP for spinup
#prep_datevalidity  = 1950080106
#prep_block         = spinup
#prep_block         = offline

[concatenation_job]
# concatenation + shadows
ntasks = 20
partition = normal256
time   = 0:10:00
mem    = 128G
geometry = postes

[concatenation]
# The "concatenation" task takes the 6 "SAFRAN-postes" native forcing files as input and concatenates them
# into a single forcing file
forcing_xpid       = release_2026.1
forcing_user       = vernaym
forcing_geometry   = list(alp27_flat,pyr24_flat,cor2_flat,mac11_flat,vog3_flat,jur4_flat)
forcing_block      = safran/postes

[shadows]
# The "shadows" task takes the single output forcing file from the "concatenation" task as input
forcing_geometry = postes
forcing_block = concatenate

[addslopes_alp]
# Use normal256 partition for an optimal parallelisation
partition = normal256
time   = 0:15:00
mem    = 128G
# The computing time seems to increase exponentially with the number of task : understand why
ntasks = 10

[addslopes_pyr]
# Use normal256 partition for an optimal parallelisation
partition = normal256
time   = 0:15:00
mem    = 128G
max_ntasks = 10

[addslopes_cor]
# Use normal256 partition for an optimal parallelisation
partition = normal256
time   = 0:O5:00
mem    = 128G
max_ntasks = 50

[addslopes_mac]
# Use normal256 partition for an optimal parallelisation
partition = normal256
time   = 0:05:00
mem    = 128G
max_ntasks = 50

[addslopes_vog]
# Use normal256 partition for an optimal parallelisation
partition = normal256
time   = 0:05:00
mem    = 128G
max_ntasks = 50

[addslopes_jur]
# Use normal256 partition for an optimal parallelisation
partition = normal256
time   = 0:05:00
mem    = 128G
max_ntasks = 50

[addslopes]
# Add slopes to "SAFRAN-flat_massif" native forcing files
forcing_xpid       = release_2026.1
forcing_user       = vernaym
forcing_geometry   = dict(alp27_allslopes:alp27_flat pyr24_allslopes:pyr24_flat cor2_allslopes:cor2_flat mac11_allslopes:mac11_flat vog3_allslopes:vog3_flat jur4_allslopes:jur4_flat)
forcing_block      = safran/massifs

[pgd_postes]
# For the "postes" geometry, get concatenated forcing files with masks from the "shadows" task
forcing_block      = shadows

# For all other geometries, get forcing files with slopes from the "addslopes" task
[pgd_alp]
forcing_block      = addslopes

[pgd_pyr]
forcing_block      = addslopes

[pgd_cor]
forcing_block      = addslopes

[pgd_mac]
forcing_block      = addslopes

[pgd_vog]
forcing_block      = addslopes

[pgd_jur]
forcing_block      = addslopes


[init_tg_alp]
forcing_block = addslopes

[init_tg_pyr]
forcing_block = addslopes

[init_tg_cor]
forcing_block = addslopes

[init_tg_mac]
forcing_block = addslopes

[init_tg_vog]
forcing_block = addslopes

[init_tg_jur]
forcing_block = addslopes

[init_tg_postes]
forcing_block = shadows

[prep_alp]
forcing_block = addslopes

[prep_pyr]
forcing_block = addslopes

[prep_cor]
forcing_block = addslopes

[prep_mac]
forcing_block = addslopes

[prep_vog]
forcing_block = addslopes

[prep_jur]
forcing_block = addslopes

[prep_postes]
forcing_block = shadows

[prep]
prep_datevalidity  = 1950080106

[spinup_alp]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 80
time               = 15:00:00
# PREP file for spinup
prep_datevalidity  = 1950080106
prep_block         = prep
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[spinup_pyr]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 80
time               = 12:00:00
# PREP file for spinup
prep_datevalidity  = 1950080106
prep_block         = prep
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[spinup_cor]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 18
time               = 03:00:00
# PREP file for spinup
prep_datevalidity  = 1950080106
prep_block         = prep
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[spinup_mac]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 66
time               = 08:00:00
# PREP file for spinup
prep_datevalidity  = 1950080106
prep_block         = prep
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[spinup_vog]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 15
time               = 03:00:00
# PREP file for spinup
prep_datevalidity  = 1950080106
prep_block         = prep
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[spinup_jur]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 24
time               = 04:00:00
# PREP file for spinup
prep_datevalidity  = 1950080106
prep_block         = prep
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[spinup_postes]
partition          = normal256
ntasks             = 80
time               = 10:00:00
# PREP file for spinup
prep_datevalidity  = 1950080106
prep_block         = prep
# FORCING files with masks from the "shadows" task
forcing_block      = shadows

[surfex_reanalysis_alp]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 80
time               = 15:00:00
# PREP file from spinup
prep_datevalidity  = 1950080106
prep_block         = spinup
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[surfex_reanalysis_pyr]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 80
time               = 12:00:00
# PREP file from spinup
prep_datevalidity  = 1950080106
prep_block         = spinup
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[surfex_reanalysis_cor]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 18
time               = 03:00:00
# PREP file from spinup
prep_datevalidity  = 1950080106
prep_block         = spinup
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[surfex_reanalysis_mac]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 66
time               = 08:00:00
# PREP file from spinup
prep_datevalidity  = 1950080106
prep_block         = spinup
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[surfex_reanalysis_vog]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 15
time               = 03:00:00
# PREP file from spinup
prep_datevalidity  = 1950080106
prep_block         = spinup
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[surfex_reanalysis_jur]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 24
time               = 04:00:00
# PREP file from spinup
prep_datevalidity  = 1950080106
prep_block         = spinup
# FORCING files with slopes from the "addslopes" task
forcing_block      = addslopes

[surfex_reanalysis_postes]
partition          = normal256
ntasks             = 80
time               = 10:00:00
# PREP file from spinup
prep_datevalidity  = 1950080106
prep_block         = spinup
# FORCING files with masks from the "shadows" task
forcing_block      = shadows
