[DEFAULT]
partition          = shared
mem                = 30G
ntasks             = 1
time               = 0:05:00
xpid               = reanalysis_era5.8_crocus3.0.2_std
forcing_xpid       = release_2026.1
forcing_user       = vernaym
namelist_source    = OPTIONS_V9_reanalysis.nam
uenv               = uenv:s2m.reanalysis_era5.8_crocus3.0.2_std@lafaysse

# Actual PREP file for entire reanalysis run
#prep_xpid          = spinup_crocus3.0.2_std
#prep_user          = lafaysse
# A écraser en ligne de commande pour une nouvelle année
prep_datevalidity  = 1950080106
# A écraser en ligne de commande pour une nouvelle année
prep_block         = spinup
#prep_block         = offline

[pgd_postes]
# Get concatenated forcing files with masks
forcing_block      = shadows
forcing_user       = vernaym
uenv               = uenv:s2m.pgd_crocus3.0.2_std@lafaysse

[concatenation_job]
# TODO : Comprendre pourquoi ça plante avec un ntasks supérieur
ntasks = 10
nprocs = 10
time   = 0:15:00
forcing_geometry   = alp27_flat,pyr24_flat,cor2_flat,mac11_flat,vog3_flat,jur4_flat
forcing_block      = safran/postes

[addslopes]
# Add slopes to SAFRAN "flat massif" native forcing files
forcing_geometry   = dict(alp27_allslopes:alp27_flat pyr24_allslopes:pyr24_flat cor2_allslopes:cor2_flat mac11_allslopes:mac11_flat vog3_allslopes:vog3_flat jur4_allslopes:jur4_flat)
forcing_block      = safran/massifs
# TODO : Comprendre pourquoi ça plante avec le ntasks du job
max_ntasks         = 20

[prep]
#xpid               = init_spinup_crocus3.0.2_std
prep_datevalidity  = 1950080106

[spinup_alp]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 80
nprocs             = 80
time               = 15:00:00
# PREP file for spinup
#prep_xpid          = init_spinup_crocus3.0.2_std
#prep_user          = lafaysse
prep_datevalidity  = 1950080106
prep_block         = prep

[spinup_pyr]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 80
nprocs             = 80
time               = 12:00:00
# PREP file for spinup
#prep_xpid          = init_spinup_crocus3.0.2_std
#prep_user          = lafaysse
prep_datevalidity  = 1950080106
prep_block         = prep

[spinup_cor]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 18
nprocs             = 18
time               = 03:00:00
# PREP file for spinup
#prep_xpid          = init_spinup_crocus3.0.2_std
#prep_user          = lafaysse
prep_datevalidity  = 1950080106
prep_block         = prep

[spinup_mac]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 66
nprocs             = 66
time               = 08:00:00
# PREP file for spinup
#prep_xpid          = init_spinup_crocus3.0.2_std
#prep_user          = lafaysse
prep_datevalidity  = 1950080106
prep_block         = prep

[spinup_vog]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 15
nprocs             = 15
time               = 03:00:00
# PREP file for spinup
#prep_xpid          = init_spinup_crocus3.0.2_std
#prep_user          = lafaysse
prep_datevalidity  = 1950080106
prep_block         = prep

[spinup_jur]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 24
nprocs             = 24
time               = 04:00:00
# PREP file for spinup
#prep_xpid          = init_spinup_crocus3.0.2_std
#prep_user          = lafaysse
prep_datevalidity  = 1950080106
prep_block         = prep

[spinup_postes]
partition          = normal256
ntasks             = 80
nprocs             = 80
time               = 10:00:00
# PREP file for spinup
#prep_xpid          = init_spinup_crocus3.0.2_std
#prep_user          = lafaysse
prep_datevalidity  = 1950080106
prep_block         = prep
# Get concatenated forcing files with masks
forcing_block      = shadows

[surfex_reanalysis_alp]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 80
nprocs             = 80
time               = 15:00:00

[surfex_reanalysis_pyr]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 80
nprocs             = 80
time               = 12:00:00

[surfex_reanalysis_cor]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 18
nprocs             = 18
time               = 03:00:00

[surfex_reanalysis_mac]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 66
nprocs             = 66
time               = 08:00:00

[surfex_reanalysis_vog]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 15
nprocs             = 15
time               = 03:00:00

[surfex_reanalysis_jur]
# Parallélisation MPI optimale pour la taille du domaine
partition          = normal256
ntasks             = 24
nprocs             = 24
time               = 04:00:00

[surfex_reanalysis_postes]
partition          = normal256
ntasks             = 80
nprocs             = 80
time               = 10:00:00
# Get concatenated forcing files with masks
forcing_block      = shadows
