[DEFAULT]
#partition          = shared
#mem                = 30G
partition          = normal256
uenv               = uenv:s2m.reanalysis_era5.8@vernaym
xpid               = release_2026.1
forcing_xpid       = release_2026.1
forcing_user       = vernaym
namelist_source    = OPTIONS_V9_reanalysis.nam
prep_xpid          = release_2026.1
prep_user          = vernaym

[obs_safran_alp]
ntasks             = 120
time               = 06:00:00

[obs_safran_pyr]
ntasks             = 120
time               = 06:00:00

[obs_safran_cor]
ntasks             = 120
time               = 06:00:00

[obs_safran_mac]
ntasks             = 120
time               = 06:00:00

[obs_safran_vog]
ntasks             = 120
time               = 06:00:00

[obs_safran_jur]
ntasks             = 120
time               = 06:00:00

[obs_safran]
xpid               = GRIN_2700E_1940-2026_SELECT

[safran_reanalysis_alp]
# Parallélisation sur les années (1 task / year)
ntasks             = 90
time               = 07:00:00

[safran_reanalysis_pyr]
# Parallélisation sur les années (1 task / year)
ntasks             = 90
time               = 06:00:00

[safran_reanalysis_cor]
# Parallélisation sur les années (1 task / year)
ntasks             = 90
time               = 04:00:00

[safran_reanalysis_mac]
# Parallélisation sur les années (1 task / year)
ntasks             = 90
time               = 05:30:00

[safran_reanalysis_vog]
# Parallélisation sur les années (1 task / year)
ntasks             = 90
time               = 04:00:00

[safran_reanalysis_jur]
# Parallélisation sur les années (1 task / year)
ntasks             = 90
time               = 05:00:00

[safran]
# TODO : check if model still necessary
model              = safran
# TODO : check if necessary
namespace          = vortex.multi.fr
# la variable 'execution' permet de régler les ebauches de rr par type de temps (execution=reanalysis) ou avec les guess (execution=analysis)
execution          = reanalysis
cumul              = 6
guess_geometry     = dict(alp27_flat: alp pyr24_flat:pyr cor2_flat:cor mac11_flat: mac vog3_flat: vog jur4_flat: jur)
obs_geometry       = dict(alp27_flat: alp pyr24_flat:pyr cor2_flat:cor mac11_flat: mac vog3_flat: vog jur4_flat: jur)
uenv               = uenv:s2m.reanalysis_era5.8@vernaym
assim              = True
obs_xpid           = GRIN_2700E_1940-2026_SELECT
obs_user           = monteirod
obs_vapp           = safran

[surfex_reanalysis_alp]
# Parallélisation MPI optimale pour la taille du domaine
ntasks             = 80
time               = 15:00:00

[surfex_reanalysis_pyr]
# Parallélisation MPI optimale pour la taille du domaine
ntasks             = 80
time               = 12:00:00

[surfex_reanalysis_cor]
# Parallélisation MPI optimale pour la taille du domaine
ntasks             = 18
time               = 03:00:00

[surfex_reanalysis_mac]
# Parallélisation MPI optimale pour la taille du domaine
ntasks             = 66
time               = 08:00:00

[surfex_reanalysis_vog]
# Parallélisation MPI optimale pour la taille du domaine
ntasks             = 15
time               = 03:00:00

[surfex_reanalysis_jur]
# Parallélisation MPI optimale pour la taille du domaine
ntasks             = 24
time               = 04:00:00

[prep_alp]
partition          = shared
mem                = 30G
ntasks             = 80
time               = 0:05:00

[prep_pyr]
partition          = shared
mem                = 30G
ntasks             = 80
time               = 0:05:00

[prep_cor]
partition          = shared
mem                = 30G
ntasks             = 18
time               = 0:05:00

[prep_mac]
partition          = shared
mem                = 30G
ntasks             = 66
time               = 0:05:00

[prep_vog]
partition          = shared
mem                = 30G
ntasks             = 15
time               = 0:05:00

[prep_jur]
partition          = shared
mem                = 30G
ntasks             = 24
time               = 0:05:00

[pgd_alp]
partition          = shared
mem                = 30G
ntasks             = 80
time               = 0:05:00

[pgd_pyr]
partition          = shared
mem                = 30G
ntasks             = 80
time               = 0:05:00

[pgd_cor]
partition          = shared
mem                = 30G
ntasks             = 18
time               = 0:05:00

[pgd_mac]
partition          = shared
mem                = 30G
ntasks             = 66
time               = 0:05:00

[pgd_vog]
partition          = shared
mem                = 30G
ntasks             = 15
time               = 0:05:00

[pgd_jur]
partition          = shared
mem                = 30G
ntasks             = 24
time               = 0:05:00

[addslopes]
forcing_geometry   = dict(alp27_allslopes:alp27_flat pyr24_allslopes:pyr24_flat cor2_allslopes:cor2_flat mac11_allslopes:mac11_flat vog3_allslopes:vog3_flat jur4_allslopes:jur4_flat)
forcing_block      = safran/massifs
# Store SURFEX-ready FORCING files in a "meteo" block
out_block          = meteo
# TODO : Comprendre pourquoi ça plante avec le ntasks du job
max_ntasks         = 20

[init_tg_postes]
nnodes             = 1
ntasks             = 1
nprocs             = 1

[inittg]

[surfex_reanalysis_postes]
ntasks             = 80
nprocs             = 80
time               = 10:00:00

[prep_postes]
partition          = shared
mem                = 30G
nnodes             = 1
ntasks             = 1
nprocs             = 1
time               = 0:05:00

[pgd_postes]
partition          = shared
mem                = 30G
nnodes             = 1
ntasks             = 1
nprocs             = 1
time               = 0:05:00
# The generation of a PGD file requires a concateanted FORCING file in geometry "postes"
forcing_block      = concatenate
forcing_user       = vernaym

[concatenation_job]
# TODO : Comprendre pourquoi ça plante avec un ntasks supérieur
ntasks = 10
nprocs = 10
time   = 0:15:00

[concatenation]
forcing_geometry   = alp27_flat,pyr24_flat,cor2_flat,mac11_flat,vog3_flat,jur4_flat
forcing_block      = safran/postes

[shadows]
# The "concatenate" task store the concatenated FORCING under a 'concatenate' block by default
forcing_block      = concatenate
forcing_user       = vernaym
# Store SURFEX-ready FORCING files in a "meteo" block
out_block          = meteo

[offline]
nnodes             = 1
ntasks             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
nprocs             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)

[preprocess]
forcing_block      = meteo
