[DEFAULT]
python            = /opt/softs/anaconda3/envs/Py37nomkl/bin/python
nproc              = 120
ntasks             = 120
openmp             = 1
nnodes             = 1
guess_block        = guess
cpl_geometry       = euroc25
cumul              = 6
model              = safran
namespace          = vortex.multi.fr
source_app         = arpege
deterministic_conf = 4dvarfr
eps_conf           = pearp
ana_terms          = 0-24-6
# la variable 'execution' permet de régler les ebauches de rr par type de temps (execution=reanalysis) ou avec les guess (execution=analysis)
execution          = reanalysis
extrapythonpath    = epygram
cutoff             = assimilation

[safran_reanalysis_alp]
nnodes             = 1
nprocs             = 80
ntasks             = 80
time               = 05:00:00

[safran_reanalysis_pyr]
nnodes             = 1
nprocs             = 80
ntasks             = 80
time               = 04:00:00

[safran_reanalysis_cor]
nnodes             = 1
nprocs             = 18
ntasks             = 18
time               = 02:00:00

[safran_reanalysis_mac]
nnodes             = 1
nprocs             = 66
ntasks             = 66
time               = 02:30:00

[safran_reanalysis_vog]
nnodes             = 1
nprocs             = 15
ntasks             = 15
time               = 02:00:00

[safran_reanalysis_jur]
nnodes             = 1
nprocs             = 24
ntasks             = 24
time               = 03:00:00

[safran]
guess_geometry     = dict(alp27_flat: alp pyr24_flat:pyr cor2_flat:cor mac11_flat: mac vog3_flat: vog jur4_flat: jur)
obs_geometry       = dict(alp27_flat: alp pyr24_flat:pyr cor2_flat:cor mac11_flat: mac vog3_flat: vog jur4_flat: jur)
cycle              = uenv:s2m.reanalysis_era5.6@vernaym
assim              = True
obs_xpid           = GRIN_2700E_1940-2024_SELECT
obs_user           = monteirod
obs_vapp           = safran

[surfex_reanalysis_alp]
nnodes             = 1
nprocs             = 80
ntasks             = 80
time               = 11:00:00

[surfex_reanalysis_pyr]
nnodes             = 1
nprocs             = 80
ntasks             = 80
time               = 09:00:00

[surfex_reanalysis_cor]
nnodes             = 1
nprocs             = 18
ntasks             = 18
time               = 02:00:00

[surfex_reanalysis_mac]
nnodes             = 1
nprocs             = 66
ntasks             = 66
time               = 06:00:00

[surfex_reanalysis_vog]
nnodes             = 1
nprocs             = 15
ntasks             = 15
time               = 02:00:00

[surfex_reanalysis_jur]
nnodes             = 1
nprocs             = 24
ntasks             = 24
time               = 03:00:00

[addslopes]
forcing_geometry   = dict(alp27_allslopes:alp27_flat pyr24_allslopes:pyr24_flat cor2_allslopes:cor2_flat mac11_allslopes:mac11_flat vog3_allslopes:vog3_flat jur4_allslopes:jur4_flat)
forcing_block      = massifs
max_ntasks         = 20

[offline]
genv               = uenv:s2m.reanalysis_era5.6@vernaym
namelist_source    = OPTIONS_V9_reanalysis.nam
prep_xpid          = spinup
prep_user          = lafaysse
prep_vconf         = [geometry:tag]
prep_vortex1       = True

