[build-system]
requires = ["setuptools>=66,<71"]
build-backend = "setuptools.build_meta"

[project]
name = "snowtools"
version = "2.0.4"
dependencies = [
    'numpy>=1.8',
    'cftime',
    'certifi',
    'netCDF4',
    'scipy',
    'python-dateutil',
    'pyproj',
    'shapely',
    'pyshp',
    'pandas<=2.3.2',
    'xarray>=0.18.0',  # Enable the use of snowtools xarray plugin
    'bronx',
    'footprints',
    'packaging',
    'epygram>=2.0',
]
requires-python = ">=3.6"
readme = "README.md"
description = "Snowtools is a recommended python package to pre-process, run and post-process simulations with the SURFEX-Crocus snowpack model."
license = {file = "LICENCE.txt"}
classifiers=[
    'Operating System :: POSIX :: Linux',

    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',

    'Topic :: Scientific/Engineering',
]
authors = [
    {name = "Snowtools team, leaded by Matthieu Lafaysse, Meteo-France"}
]
maintainers = [
    {name = "Snowtools team, leaded by Matthieu Lafaysse, Meteo-France"}
]

[project.optional-dependencies]
# To enable the use of MF's databases extraction tools
sql = [
    'psycopg2',  # psycopg2 not available on MF's HPC because there is not pg_config executable
# Error message :
# If you prefer to avoid building psycopg2 from source, please install the PyPI
# 'psycopg2-binary' package instead.
#    'psycopg2-binary',
]

# To enable the use of graphic tools
plot = [
    'matplotlib',
    'cartopy',
    'rioxarray',
]

scores = [
    'snowtools-crps@git+https://github.com/UMR-CNRM/snowtools-crps.git',
]

vortex = [
    'vortex-nwp@git+https://github.com/UMR-CNRM/vortex.git@e5a166f83c2f75d71f9cbf41c6acfa961f1f59f8',  # A remplacer par 'vortex-nwp' dès que possible avec versionnement > 2.4.1
]

hpc = [
    'scikit-learn',  # For SAFRAN guess generation (used in a task that call a non-properly installed script which do not manage its dependencies)
    'vortex-nwp@git+https://github.com/UMR-CNRM/vortex.git@e5a166f83c2f75d71f9cbf41c6acfa961f1f59f8',  # A remplacer par 'vortex-nwp' dès que possible avec versionnement > 2.4.1
    'mkjob@file:///home/cnrm_other/cen/mrns/vernaym/Projects/mkjob',
    'vortex-gco@file:///home/cnrm_other/cen/mrns/vernaym/Projects/vortex-gco',
    'vortex-olive@file:///home/cnrm_other/cen/mrns/vernaym/Projects/vortex-olive',
]

doc = [
    'sphinx>=4.3',
    'sphinx-fortran@git+https://github.com/VACUMM/sphinx-fortran.git',
    'sphinx-toolbox',
    'graphviz',
    'mkjob@git+http://gitlab.meteo.fr/cnrm-gmap/mkjob.git',
    'vortex-gco@git+https://gitlab.meteo.fr/cnrm-gmap/vortex-gco.git'
]

# For a full installation
all = [
    'vortex-nwp@git+https://github.com/UMR-CNRM/vortex.git@e5a166f83c2f75d71f9cbf41c6acfa961f1f59f8',  # A remplacer par 'vortex-nwp' dès que possible avec versionnement > 2.4.1
    'psycopg2',
    'matplotlib',
    'cartopy',
    'rioxarray',
    'snowtools-crps@git+https://github.com/UMR-CNRM/snowtools-crps.git',
]

[project.urls]
Homepage = "https://github.com/UMR-CNRM/snowtools"
Repository = "https://github.com/UMR-CNRM/snowtools"

[project.scripts]
s2m = 'snowtools.tasks.s2m_command:main'
proplotter = 'snowtools.plots.stratiprofile.proplotter:main'
mapplotter = 'snowtools.plots.maps.mapplotter:main'
procompare = 'snowtools.plots.stratiprofile.procompare:main'
mkjob-help = 'vortex_cen.scripts.mkjob_help:main'
s2m_oper = 'vortex_cen.scripts.s2m_oper:main'
s2m_reanalysis = 'vortex_cen.scripts.s2m_reanalysis:main'
get_simulation_output = 'vortex_cen.scripts.get_simulation_output:main'

[project.entry-points."xarray.backends"]
snowtools = "snowtools.utils.xarray_snowtools_backend:SnowtoolsBackendEntrypoint"

[project.entry-points.vtx]
cen = "vortex_cen"

[tool.setuptools.package-dir]
vortex_cen = "vortex_cen"

[tool.setuptools.package-data]
"vortex_cen.data.cen_stores_configs" = ["cen-map-resources.ini"]
"vortex_cen" = ["**/*.job", "**/*.jobs", "**/*.ini"]

[tool.setuptools.packages.find]
# Explicitely exclude the "cenutils" repository from the setuptool automatic package discovery
# The editable installation on soprano crashes without this statement:
# `error: Multiple top-level packages discovered in a flat-layout: ['bronx', 'cenutils', 'snowtools'].`
exclude = ["cenutils"]
