[DEFAULT]
# Default job configuration (all jobs)
# ------------------------------------
# Single-node:
partition          = shared
mem                = 90G
# Default binding for standard S2M geometries
nnodes             = 1
ntasks             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
nprocs             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
# Multi-nodes:
#partition          = normal256
#

[croco]
# job configuration
partition          = normal256
# Default GEnv
uenv               = uenv:s2m.reanalysis_era5.8@vernaym
namelist_source    = OPTIONS_V9_reanalysis.nam
#
# Configuration from B. Delacroix experiment
stopdates          = 2018041618,2018080106
members            = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
members_id         = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
nmembers           = 35
subensemble        = E2

[offline]

[soda]

[preprocess]
# Absolute path to local namelist
# WARNING : simulation reproductibility is not guaranteed
#namelist_path      =
# For reproductible simulations, use a namelist from a UEnv
#namelist_genv      =
#namelist_source    =

