[DEFAULT]

# Default job configuration (all jobs)
# ------------------------------------
# Single-node:
partition          = shared
mem                = 90G
# Default binding for standard S2M geometries
nnodes             = 1
ntasks             = 80
nprocs             = 80

xpid               = testopenloop
uenv               = uenv:s2m_croco_testcase@vernaym
namelist_source    = OPTIONS_croco.nam
# TODO : "nmembers" pourrait / devrait être déduit de "member"
nmembers           = 35

# model in mandatory here beacause of the default value set in WorkshareFamily and LoopFamily nodes
model = unknown

# FORCING
forcing_vapp        = safran
forcing_vconf       = postes_12_csv
forcing_xpid        = forcing_20132014B_31D_11_t1500_160
forcing_user        = fructusm
forcing_block       = meteo
forcing_member      = rangex(start:1 end:35 step:1)
forcing_vortex1     = True
# "forcing_dateend" est différent de "dateend"
forcing_dateend     = 2014080106

# PREP
prep_xpid            = spinup
prep_user            = fructusm
prep_vapp            = s2m
prep_vconf           = postes_12_csv
prep_block           = prep
prep_datevalidity    = 2016080106
prep_vortex1         = True

# PGD
pgd_xpid            = spinup
pgd_user            = fructusm
pgd_vapp            = s2m
pgd_vconf           = postes_12_csv
pgd_block           = pgd

[croco_openloop]
#openloop=True
# Assimdate is mandatory and must be an empty list in the openloop case
assimdates=list()
members=rangex(start:1 end:35)
members_id = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35

[croco_assim]
assimdates=list(2018030106)
members=rangex(start:1 end:35)
members_id = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
scope = slb

# Observations
observatin_vapp = s2m
observation_vconf = postes_12_csv
observation_xpid =  obs
observation_user = fructusm
observation_block = 12

[offline]

[soda]

[fetch_pgd]

[fetch_prep]


