[DEFAULT]

# Default job configuration (all jobs)
# ------------------------------------
# Single-node:
partition          = shared
mem                = 90G
# Default binding for standard S2M geometries
nnodes             = 1
ntasks             = 80
nprocs             = 80

xpid               = testopenloop
uenv               = uenv:s2m_croco_testcase@vernaym
surfex_uenv        = uenv:surfex_executables_mpiauto_ba8b12ae@vernaym
# TODO : "nmembers" pourrait / devrait être déduit de "member"
nmembers           = 35

# model in mandatory here beacause of the default value set in WorkshareFamily and LoopFamily nodes
model = unknown

# FORCING
forcing_vapp        = s2m
forcing_vconf       = grandesrousses
forcing_xpid        = perturb.reanalysis2020.2
forcing_user        = lafaysse
forcing_block       = meteo
forcing_member      = rangex(start:1 end:35 step:1)
forcing_vortex1     = True

# PGD
pgd_xpid            = spinup
pgd_user            = fructusm
pgd_vapp            = s2m
pgd_vconf           = grandesrousses
pgd_block           = pgd
pdg_vortex1         = True

[croco_openloop]
#openloop=True
# Assimdate is mandatory and must be an empty list in the openloop case
assimdates=list()
members=rangex(start:1 end:35)
members_id = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
namelist_source    = OPTIONS_croco_openloop.nam
prep_block           = prep_refill

[croco_assim]
assimdates=list(2020030618,2020031818,2020033018)
members=rangex(start:1 end:35)
members_id = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35
scope = slb
namelist_source = OPTIONS_croco_assim_rlocal.nam

# Observations
observation_vapp = s2m
observation_vconf = grandesrousses
observation_xpid =  obs
observation_user = fructusm
observation_block = S1_Magenta_fine_no40_slb

[offline]
prep_block           = prep_refill

[soda]
soda_gvar = master_soda_mpi

[fetch_pgd]

[prep_refill]
# Fetch initial PREP file to start the simulation
prep_xpid            = spinup
prep_user            = fructusm
prep_vapp            = s2m
prep_vconf           = grandesrousses
prep_block           = prep
prep_datevalidity    = 2019080106
prep_vortex1         = True
