[DEFAULT]
nmembers = 17
geometry = GrandesRousses250m
xpid = TEST_assim
# Common configuration variables for all tasks
pgd_vapp = edelweiss
pgd_vconf = grandesrousses250m
pgd_xpid = spinup_V9
pgd_user = vernaym
pgd_vortex1 = True
genv = uenv:edelweiss_gr250_pappus.6@vernaym
forcing_vapp = edelweiss
forcing_vconf = grandesrousses250m
forcing_xpid = ALPAGA
forcing_user = vernaym
forcing_vortex1 = True

[preprocess]
namelist_source = OPTIONS_OFFLINE_V9.nam

[offline_openloop_job]
# This is the configuration for the offline_openloop job (offline_preprocess + offline_openloop tasks)
nnodes = 1
nprocs = 100
ntasks = 100
time = 01:00:00

[offline_openloop]
# This is the configuration of the initial SURFEX ensemble simulation, before any data assimilation
prep_xpid = spinup_V9
prep_user = vernaym
prep_vapp = edelweiss
prep_vconf = grandesrousses250m
prep_vortex1 = True

[offline_assim_job]
# This is the configuration for the offline_openloop job (offline_preprocess + offline_assim tasks)
nnodes = 1
nprocs = 100
ntasks = 100
time = 01:00:00

[offline_assim]
# This is the configuration of SURFEX ensemble simulations after data assimilation
prep_block = prep/analysis
namelist_source = OPTIONS_OFFLINE_V9.nam

[soda_job]
time = 0:05:00
exclusive =
nnodes = 1
nprocs = 1
ntasks = 1
openmp = 1

[soda_preprocess]
# This is the configuration of the SODA namelist pre-processing task
namelist_source = OPTIONS_SODA_V9_ERR_05.nam

[soda]
# This is the configuration of the SODA assimilation task
sensor =
observation_vapp = Pleiades
observation_vconf = grandesrousses250m
observation_xpid = CesarDB
observation_user = vernaym
members = 0-16-1
