[DEFAULT]
nmembers = 17
geometry = GrandesRousses250m
xpid = open_loop
# Common configuration variables for all tasks
pgd_vapp = edelweiss
pgd_vconf = grandesrousses250m
pgd_xpid = spinup_V9
pgd_user = vernaym
pgd_vortex1 = True
genv = uenv:edelweiss_gr250_open_loop.0@imperatoren
forcing_vapp = edelweiss
forcing_vconf = grandesrousses250m
forcing_xpid = ALPAGA
forcing_user = vernaym
forcing_vortex1 = True

[preprocess]
namelist_source = OPTIONS_OFFLINE_V9.nam

[offline_openloop_job]
# This is the configuration for the offline_openloop job (offline_preprocess + offline_openloop tasks)
nnodes = 1
nprocs = 100
ntasks = 100
time = 01:00:00

[offline_openloop]
# This is the configuration of the initial SURFEX ensemble simulation, before any data assimilation
prep_xpid = spinup_V9
prep_user = vernaym
prep_vapp = edelweiss
prep_vconf = grandesrousses250m
prep_vortex1 = True


