[DEFAULT]
forcing_vapp = s2m
forcing_vconf = cor
forcing_geometry = cor
forcing_namebuild = date@std
forcing_xpid = OPER
forcing_vortex1 = True
forcing_datebegin = 2025080106
forcing_dateend = 2026061806
forcing_date = 2026062212
forcing_cutoff = assimilation
forcing_block = meteo
forcing_model = s2m
forcing_alternate = False
io_duration = full

[surfex_dailyprep_cor]
time = 0:20:00

[preprocess_uenv_namelist]
uenv = uenv:testbase_uenv.07@vernaym
namelist_source = OPTIONS_V9_reference.nam

[offline_mpi_dailyprep]
uenv = uenv:testbase_uenv.07@vernaym
pgd_xpid = double_2026
prep_xpid = double_2026
prep_vconf = cor2_allslopes
prep_member = None
prep_datevalidity = 2020080106
nnodes = 1
nprocs = dict(cor:18 cor2_allslopes:18)
ntasks = dict(cor:18 cor2_allslopes:18)
openmp = 1


[getprep]
uenv = uenv:testbase_uenv.07@vernaym
prep_vapp = s2m
prep_vconf = cor2_allslopes
prep_xpid = reanalysis_era5_reconstructed_obs_v2_crocus3.0
prep_user = lafaysse
prep_vortex1 = True
prep_namebuild = flat@cen
prep_member = None
prep_cutoff = None
prep_datevalidity = 2020080106
xpid_tg = OPER
pgd_xpid = OPER

[getpgd1d]
uenv = uenv:testbase_uenv.07@vernaym
# geometry = cor_allslopes
# genv_pgd = uenv:cen01_cen@s2m-op2.13
force_uenv = True
