[DEFAULT]
forcing_vapp = s2m
forcing_vconf = cor
forcing_geometry = cor
forcing_namebuild = None
forcing_xpid = OPER
forcing_vortex1 = True
forcing_datebegin = 2025080106
forcing_dateend = 2026051806
forcing_date = 2026052212
forcing_cutoff = assimilation
forcing_block = meteo
forcing_model = s2m
forcing_alternate = False

[surfex_dailyprep_cor]
time = 0:20:00

[preprocess_uenv_namelist]
genv = uenv:testbase_uenv.04@radanovicss
namelist_source = OPTIONS_V9_reference.nam

[offline_mpi_dailyprep]
genv = uenv:testbase_uenv.04@radanovicss
pgd_xpid = double_2026
prep_xpid = double_2026
prep_vconf = cor2_allslopes
prep_member = None
prep_datevalidity = 2020080106
nnodes = 1
nprocs = dict(cor:18 cor2_allslopes:18)
ntasks = dict(cor:18 cor2_allslopes:18)
openmp = 1


[getprep]
genv = uenv:testbase_uenv.04@radanovicss
prep_vapp = s2m
prep_vconf = cor2_allslopes
prep_xpid = reanalysis_era5_reconstructed_obs_v2_crocus3.0
prep_user = lafaysse
prep_vortex1 = True
prep_namebuild = flat@cen
prep_member = None
prep_cutoff = None
prep_datevalidity = 2020080106
xpid_tg = OPER
pgd_xpid = OPER
nnodes = 1
nprocs = 60
ntasks = 60
openmp = 1

[getpgd1d]
genv = uenv:testbase_uenv.04@radanovicss
# geometry = cor_allslopes
# genv_pgd = uenv:cen01_cen@s2m-op2.13
genv_pgd = uenv:testbase_uenv.04@radanovicss
nnodes = 1
nprocs = 60
ntasks = 60
openmp = 1
