# -*- coding: utf-8 -*
"""
The s2m "reanalysis" configuration
----------------------------------

SAFRAN-SURFEX/Crocus-Mepra (S2M) reanalysis simulations (reference dataset and research SURFEX simulations
based on the reference SAFRAN reanalysis)

Workflow:
^^^^^^^^^

1. SAFRAN inputs

* obs_safran : Generation of SAFRAN-compatible reconstructed hourly surface observation time series

* prepsafran : Generation of SAFRAN guess files

2. FORCING generation

* safran : Generation of "raw" SAFRAN meteorological forcing files ("flat" geometry and 1 "postes" FORCING file per domain)

* add_slopes : Add slopes and aspects to the raw "flat" SAFRAN meteorological forcing files

.. code-block::

    mkjob -c ~/snowtools/vortex_cen/s2m/reanalysis/conf/crocus3.0.2.ini -f ~/snowtools/vortex_cen/s2m/reanalysis/jobs/add_slopes.jobs -a datebegin=1940080106 dateend=2025080106 -n addslopes_vog
..

.. note::

    To launch all 6 domains, remove "-n addslopes_vog" from the previous command line
..

* concatenation_postes : Concatenate "postes" forcing files from all domains into a single FORCING file and add solar masks

.. code-block::

    mkjob -c ~/snowtools/vortex_cen/s2m/reanalysis/conf/crocus3.0.2.ini -f ~/snowtools/vortex_cen/s2m/reanalysis/jobs/concatenation.jobs -a datebegin=1940080106 dateend=2025080106
..

3.Generation of PGD.nc and PREP.nc files (only once)

* Generation of ground physiography :

.. code-block::

    mkjob -c ~/snowtools/vortex_cen/s2m/reanalysis/conf/crocus3.0.2.ini -f ~/snowtools/vortex_cen/s2m/reanalysis/jobs/pgd.jobs -a forcing_datebegin=1950080106 forcing_dateend=1951080106 -n pgd_postes
..

.. note::

    You need to add the produced PGD.nc file in your uenv to be able to use it in the next steps
..

* Generation of an initial ground temperature

.. code-block::

    mkjob -c ~/snowtools/vortex_cen/s2m/reanalysis/conf/crocus3.0.2.ini -f ~/snowtools/vortex_cen/s2m/reanalysis/jobs/init_TG.jobs -a forcing_datebegin=1950080106 forcing_dateend=1951080106 -n init_tg_vog
..

.. note::

    You need to add the produced init_TG.nc file in your uenv to be able to use it in the next steps.
    TODO : check if really necessary
..

* Generation of an initial snowpack state (PREP.nc file) for the spinup step

.. code-block::

    mkjob -c ~/snowtools/vortex_cen/s2m/reanalysis/conf/crocus3.0.2.ini -f ~/snowtools/vortex_cen/s2m/reanalysis/jobs/prep.jobs -a prep_datevalidity=1950080106 datebegin=1950080106 dateend=1951080106 -n prep_vog
..

* Spinup : generation of more physical initial conditions to use to initialise the actual reanalysis (use prep generated by the previous "prep" step)

.. code-block::

    mkjob -c ~/snowtools/vortex_cen/s2m/reanalysis/conf/crocus3.0.2.ini -f ~/snowtools/vortex_cen/s2m/reanalysis/jobs/spinup.jobs -a datebegin=1940080106 dateend=1950080106 -n spinup_vog
..

3. SURFEX

Generation of SURFEX/Crocus snowpack simulations on "allslopes" and "postes" geometries (use prep generated by the spinup step)

* Entire simulation period :

.. code-block::

    mkjob -c ~/snowtools/vortex_cen/s2m/reanalysis/conf/crocus3.0.2.ini -f ~/snowtools/vortex_cen/s2m/reanalysis/jobs/surfex.jobs -a datebegin=1940080106 dateend=2025080106 -n surfex_reanalysis_vog
..

* To add only one year (use prep generated by the last execution of surfex)

.. code-block::

    mkjob -c ~/snowtools/vortex_cen/s2m/reanalysis/conf/crocus3.0.2.ini -f ~/snowtools/vortex_cen/s2m/reanalysis/jobs/surfex.jobs -a prep_datevalidity=2025080106 prep_block=offline datebegin=2025080106 dateend=2026080106 -n surfex_reanalysis_vog
..

"""
