[data-tree]
rootdir = "/home/%usr%/NO_SAVE/cache/vortex"

[storage]
address="hendrix.meteo.fr"
protocol="ftp"
rootdir="~%usr%/vortex"
op_rootdir="/chaine/mxpt/mxpt001/vortex"

[ftserv]
hostname_patterns="hendrix.meteo.fr"