[DEFAULT]
partition          = shared
mem                = 10G
xpid               = s2m_reanalysis_test_case

# FORCING file
forcing_vapp        = safran
forcing_vconf       = cor
forcing_xpid        = reanalysis2020.2
forcing_user        = vernaym
forcing_block       = massifs
forcing_source_app  = arpege
forcing_source_conf = 4dvarfr
forcing_vortex1    = True


[perturbations]
time               = 0:10:00
nnodes             = 1
ntasks             = 80
nprocs             = 80
members            = 1-80-1
