[DEFAULT]
ntasks             = 128
openmp             = 1
nnodes             = 1
xpid               = reforecast_2026.1
uenv               = uenv:s2m_reforecast_2026.1@vernaym
prv_terms          = 6-102-3

[prepsafran_job]
# 1 single node is more effecient than a multi-node execution
nnodes             = 1
ntasks             = 128
time               = 2:30:00

[prepsafran]
uenv               = uenv:s2m_reforecast_2026.1@vernaym
arpege_geometry    = eurat01
pearp_geometry     = eurat01
guess_xpid         = dble
members            = 0-34-1
geometries         = alp27_flat,pyr24_flat,cor2_flat,mac11_flat,jur4_flat,vog3_flat

[safran_reforecast_alp]
nnodes             = 1
ntasks             = 128
time               = 9:00:00
geometry           = alp27_flat

[safran_reforecast_pyr]
nnodes             = 1
ntasks             = 128
time               = 7:00:00
geometry           = pyr24_flat

[safran_reforecast_cor]
nnodes             = 1
ntasks             = 128
time               = 01:30:00
geometry           = cor2_flat

[safran_reforecast_mac]
nnodes             = 1
ntasks             = 128
time               = 04:00:00
geometry           = mac11_flat

[safran_reforecast_vog]
nnodes             = 1
ntasks             = 128
time               = 01:30:00
geometry           = vog3_flat

[safran_reforecast_jur]
nnodes             = 1
ntasks             = 128
time               = 02:00:00
geometry           = jur2_flat

[safran]
members            = 0-35-1

