[DEFAULT]
# Default job configuration
# -------------------------
# Single-node:
partition          = shared
mem                = 90G
# Default binding for standard S2M geometries
nnodes             = 1
ntasks             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
nprocs             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
# Multi-nodes:
#partition          = normal256
#
# Default GEnv
# ------------
uenv               = uenv:s2m.reanalysis_era5.8@vernaym
namelist_source    = OPTIONS_V9_reanalysis.nam
#
# Default FORCING files (S2M reanalysis)
# --------------------------------------
forcing_xpid       = release_2026.1
forcing_user       = vernaym
forcing_block      = meteo
forcing_vapp       = s2m
forcing_vconf      = reanalysis

[surfex]
# SURFEX job configuration
partition          = normal256
climground         = True

[inittg]

[prep]

[pgd]

[offline]

[preprocess]
# Absolute path to local namelist
# WARNING : simulation reproductibility is not guaranteed
#namelist_path      =
# For reproductible simulations, use a namelist from a UEnv
#namelist_genv      =
#namelist_source    =
