[DEFAULT]
# Default job configuration
# -------------------------
# Single-node:
partition          = normal256
nnodes             = 1
ntasks             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:80 mac11_allslopes:80 vog3_allslopes:80 jur4_allslopes:80 postes:80 alp27_flat:80 pyr24_flat:80 cor2_flat:18 mac11_flat:66 jur4_flat:24 vog3_flat:15)
nprocs             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:80 mac11_allslopes:80 vog3_allslopes:80 jur4_allslopes:80 postes:80 alp27_flat:80 pyr24_flat:80 cor2_flat:18 mac11_flat:66 jur4_flat:24 vog3_flat:15)
#
# Default GEnv
# ------------
uenv               = uenv:s2m.reanalysis_era5.8@vernaym
namelist_source    = OPTIONS_V9_reanalysis.nam
#
# Default FORCING files (S2M reanalysis)
# --------------------------------------
forcing_xpid       = release_2026.1
forcing_user       = vernaym
forcing_block      = meteo
forcing_vapp       = s2m
forcing_vconf      = reanalysis

[surfex]
# SURFEX job configuration
climground         = True

[inittg]

[prep]

[pgd]

[offline]
