[DEFAULT]
# Job configuration for OFFLINE executable only with XIOS server
# --------------------------------------------------------------
# Single-node:
partition          = shared  # normal256, shared, huge512
mem                = 220G
nnodes = 1
nprocs = 80
ntasks = 80
io_nodes = 0
io_nproc = 6
io_tasks = 6
#io_companions = 6  # --> crash because "Binary groups are not supported by 'MpiBinaryIOServer' objects"

#
# GEnv
# ----
uenv = uenv:testbase_uenv_local@fructusm
consts_surfex_uenv = uenv:testbase_uenv_local@fructusm
#
# FORCING files for fullalpes geometry
# ------------------------------------
forcing_xpid       = bigalp250std
forcing_user       = fructusm
forcing_vapp       = meteo
forcing_vconf      = distributed
forcing_geometry   = fullalpes
forcing_datebegin  = 2020090106
forcing_dateend    = 2020110106
io_duration        = full

#
# PGD and PREP files for fullalpes geometry
# -----------------------------------------
prep_xpid          = bigalp_forcingstd
prep_user          = fructusm
prep_vapp          = Crocus
prep_vconf         = deterministic
prep_geometry      = fullalpes

pgd_xpid           = bigalp_forcingstd
pgd_user           = fructusm
pgd_vapp           = Crocus
pgd_vconf          = deterministic
pgd_geometry       = fullalpes

#
# OTHERS
# ------
geometry           = fullalpes
xpid               = test_config_xios

[offline_xios]
# SURFEX job configuration
climground         = False
time               = 6:00:00

[inittg]

[pgd]
pgd2d = True
mask2d = True

[prep]

[offline]
exesurfex = /home/cnrm_other/cen/mrns/fructusm/git/SURFEX_CEN/exe

[preprocess]
namelist_path = /home/cnrm_other/cen/mrns/fructusm/SIMU_FORCING_BIG_ALP/OPTIONS_XIOS_fullalpes_mask.nam
# Absolute path to local namelist
# WARNING : simulation reproductibility is not guaranteed
#namelist_path      =
# For reproductible simulations, use a namelist from a UEnv
#namelist_genv      =
#namelist_source    =
