[DEFAULT]
partition          = shared
mem                = 10G
uenv               = uenv:s2m_reanalysis_test_case@vernaym
namelist_source    = OPTIONS_V9_reanalysis.nam
xpid               = s2m_reanalysis_test_case
forcing_xpid       = reanalysis2020.2
forcing_user       = vernaym
forcing_vortex1    = True
prep_xpid          = reanalysis2020.2
prep_user          = lafaysse
prep_vortex1       = True
prep_datevalidity  = 2022080106

[surfex_reanalysis_alp]
# Parallélisation MPI optimale pour la taille du domaine
time               = 0:15:00
nnodes             = 1
ntasks             = 80
nprocs             = 80

[addslopes]
forcing_geometry   = dict(alp_allslopes:alp_flat)
forcing_block      = safran/massifs
forcing_vconf      = alp_allslopes
out_block          = meteo
max_ntasks         = 20

[offline]

[preprocess]
forcing_block      = meteo
