########################################
# Template for a 2d simulation on a grid
########################################
# Context:
# offline: the only executable is OFFLINE.exe
# hendrixall: PGD.nc, PREP.nc and Forcing file are in Hendrix 
# namelist is on a specific uenv
#
# Launch command:
# mkjob -c .../vortex_cen/Crocus/deterministic/conf/template_2d_grandesrousses.ini
#       -f .../vortex_cen/Crocus/deterministic/jobs/surfex.job


[DEFAULT]
# Common configuration for all tasks

# HPC configuration (ASK BEFORE CHANGE)
partition          = normal256
nnodes             = 1
# Do not change unless you have less than 80 lines or columns in your 2D grid
ntasks             = 80
nprocs             = 80

# Default GEnv
# ------------
uenv               = uenv:ref_cen.02@fructusm
namelist_source    = OPTIONS_V9_2D_GrandesRousses250m.nam

; Walltime
time = 1:00:00
#
# Input files
# --------------------------------------
forcing_xpid       = ALPAGA
forcing_user       = vernaym
forcing_block      = mb0000/meteo
forcing_vapp       = edelweiss
forcing_vconf      = grandesrousses250m
forcing_vortex1    = True

datebegin = 2018-01-01 06
dateend = 2018-01-31 06

; General config
xpid = template_2d_grandesrousses
geometry = GrandesRousses250m

[inittg]
climground         = True

[pgd]
pgd_2D             = True
# Do not change : PGD is not parallelized
nprocs             = 1
ntasks             = 1

[prep]
tg_block        = init_tg
# Do not change : PREP is not parallelized
nprocs             = 1
ntasks             = 1

[offline]
