########################################
# Template for a 2d simulation on a grid
########################################
# Context:
# offline: the only executable is OFFLINE.exe
# hendrixall: PGD.nc, PREP.nc and Forcing file are in Hendrix 
# namelist is on a specific uenv
#
# Launch command:
# mkjob -c .../vortex_cen/Crocus/deterministic/conf/template_2d_fullalpes_1_offline_hendrixall.ini
#       -f .../vortex_cen/Crocus/deterministic/jobs/surfex.job
#       -a datebegin=2020-08-01T06 dateend=2020-08-02T06


[DEFAULT]
# Common configuration for all tasks

# HPC configuration (ASK BEFORE CHANGE)
partition          = normal256
nnodes             = 1
# Do not change unless you have less than 80 lines or columns in your 2D grid
nprocs             = 80
ntasks             = 80

# Maximum time for simulation HH:MM:SS (Be parsimonious)
time               = 1:00:00

# Env
uenv               = uenv:ref_cen.02@fructusm
namelists_surfex_uenv = uenv:template_uenv.01@fructusm
namelist_source    = Namelist_big_alp_nomask.nam

# FORCING files from Hendrix
# The localisation is deduced from the following elements:
forcing_user       = fructusm
forcing_vapp       = meteo
forcing_vconf      = distributed
forcing_xpid       = Template_2d
forcing_datebegin  = 2020-08-01 06
forcing_dateend    = 2020-09-01 06
forcing_geometry   = fullalpes
# These elements the path on Hendrix where you placed the FORCING file:
# /home/forcing_user/vortex/forcing_vapp/forcing_vconf/forcing_xpid/meteo/FORCING_geometry_datebegin_dateend.nc

# PGD.nc file from Hendrix
pgd_user           = fructusm
pgd_vapp           = Crocus
pgd_vconf          = deterministic
pgd_xpid           = Template_2d_files
pgd_geometry       = fullalpes
# file is in /home/user/vortex/pgd_vapp/pgd_vconf/pgd_xpid/PGD_geometry.nc

# PREP.nc file from Hendrix
prep_user          = fructusm
prep_vapp          = Crocus
prep_vconf         = deterministic
prep_xpid          = Template_2d_files
prep_geometry      = fullalpes
# file is in /home/user/vortex/prep_vapp/prep_vconf/prep_xpid/PREP.geometry_YYYYMMDDHH.nc

# Forcing file is existing for the full period (not the case if simulation on several years)
io_duration        = full

# Other: eXPerienceID and geometry of simulation
xpid               = template_2d_fullalpes_1_offline_hendrixall
geometry           = fullalpes


# Specific configuration for the different tasks of the driver
# Only when differs from the default defined above
# ------------------------------------------------------------
[inittg]
# No creation of init_TG.nc because PREP.nc is on Hendrix (this is default, you can suppress this line)
climground         = False

[pgd]
# For simulation on 2D grid
pgd_2D             = True
# Do not change : PGD is not parallelized
nprocs             = 1
ntasks             = 1

[prep]
# PREP.nc is on Hendrix, nothing to do
# Do not change : PREP is not parallelized
nprocs             = 1
ntasks             = 1

[offline]
# OFFLINE executable from a path
allow_path         = True
exesurfex          = /home/cnrm_other/cen/mrns/fructusm/git/SURFEX_CEN/exe
