########################################
# Template for a 2d simulation on a grid
########################################
# Context:
# exeall: ie complete simulation with PGD.exe, PREP.exe and OFFLINE.exe
# localall: ie namelist and executable are on path defined by user 
# Forcing file is on Hendrix
#
# Launch command:
# mkjob -c .../vortex_cen/Crocus/deterministic/conf/template_2d_fullalpes_2_exeall_localall.ini
#       -f .../vortex_cen/Crocus/deterministic/jobs/surfex.job
#       -a datebegin=2020-08-01T06 dateend=2020-08-02T06


[DEFAULT]
# Common configuration for all tasks

# HPC configuration (ASK BEFORE CHANGE)
partition          = normal256
nnodes             = 1
# Do not change unless you have less than 80 lines or columns in your 2D grid
nprocs             = 80
ntasks             = 80

# Maximum time for simulation HH:MM:SS (Be parsimonious)
time               = 1:00:00

# Env
uenv               = uenv:ref_cen.02@fructusm

# FORCING files from Hendrix
# The localisation is deduced from the following elements:
forcing_user       = fructusm
forcing_vapp       = meteo
forcing_vconf      = distributed
forcing_xpid       = Template_2d
forcing_datebegin  = 2020-08-01 06
forcing_dateend    = 2020-09-01 06
forcing_geometry   = fullalpes
# These elements the path on Hendrix where you placed the FORCING file:
# /home/forcing_user/vortex/forcing_vapp/forcing_vconf/forcing_xpid/meteo/FORCING_geometry_datebegin_dateend.nc

# Forcing file is existing for the full period (not the case if simulation on several years)
io_duration        = full

# Namelist from a path
allow_path         = True
namelist_path      = /home/cnrm_other/cen/mrns/fructusm/SIMU_FORCING_BIG_ALP/Namelist_big_alp_nomask.nam

# SURFEX binaries from a path (PGD, PREP, OFFLINE)
exesurfex          = /home/cnrm_other/cen/mrns/fructusm/git/SURFEX_CEN/exe

# Other: eXPerience ID and geometry of simulation
xpid               = template_2d_fullalpes_2_exeall_localall
geometry           = fullalpes


# Specific configuration for the different tasks of the driver
# Only when differs from the default defined above
# ------------------------------------------------------------
[inittg]
# For the creation of init_TG.nc file from FORCING
climground         = True

[pgd]
# For simulation on 2D grid
pgd_2D             = True
# Do not change : PGD is not parallelized
nprocs             = 1
ntasks             = 1

[prep]
# In order to get init_TG.nc file from cache: the result of [init_tg] task is in block init_tg
tg_block           = init_tg
# Do not change : PREP is not parallelized
nprocs             = 1
ntasks             = 1

[offline]
