[DEFAULT]
# Default job configuration
# -------------------------
# Single-node:
partition          = shared
mem                = 90G
# Default binding for standard S2M geometries
nnodes             = 1
ntasks             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
nprocs             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
# Default GEnv with SURFEX-V8 executables and namelists
# -----------------------------------------------------
uenv               = uenv:surfex_v8@vernaym
namelist_source    = OPTIONS_default.nam
#
# Default FORCING files (S2M reanalysis)
# --------------------------------------
forcing_xpid       = release_2026.1
forcing_user       = vernaym
forcing_block      = meteo
forcing_vapp       = s2m
forcing_vconf      = reanalysis

[prep]

[pgd]

[refill_prep]
prep_xpid = coldstart_chaine_oper
prep_user = vernaym
prep_datevalidity = 2024080106
prep_vapp = Crocus
prep_vconf = deterministic
geometry = postes
cutoff = assimilation
rundate = 2026063003
datevalidity = 2026062606
members = 0-36-1
xpid = evolution_oper_2026

