[DEFAULT]
# Default job configuration (all jobs)
# ------------------------------------
# Single-node:
partition          = shared
mem                = 90G
# Default binding for standard S2M geometries
nnodes             = 1
ntasks             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
nprocs             = dict(alp27_allslopes:80 pyr24_allslopes:80 cor2_allslopes:18 mac11_allslopes:66 vog3_allslopes:15 jur4_allslopes:24 postes:80)
# Multi-nodes:
#partition          = normal256
#

[escroc]
# SURFEX job configuration
partition          = normal256
# Allow for climground / PREP generation
climground         = True
# Default ensemble members from 1 to 36
nmembers           = 35
subensemble        = E2
# Default GEnv
uenv               = uenv:s2m.reanalysis_era5.8@vernaym
namelist_source    = OPTIONS_V9_reanalysis.nam
#
# Default FORCING files (ESM-SnowMIP in Col de Porte)
forcing_xpid       = obs
forcing_user       = lafaysse
forcing_block      = meteo
forcing_vapp       = ESM-SnowMIP
forcing_vconf      = cdp
forcing_vortex1    = True
# Default PREP file
prep_vapp          = s2m
prep_vconf         = cdp
prep_xpid          = spinup
prep_user          = lafaysse
prep_date          = 2014100100
prep_vortex1       = True
# The ESM-SnowMIP FORCING file cover the entire simulation period
# change io_duration to 'yearly' if necessary in your use case
io_duration        = full

[inittg]

[prep]

[pgd]

[escroc_task]

[preprocess]
# Absolute path to local namelist
# WARNING : simulation reproductibility is not guaranteed
#namelist_path      =
# For reproductible simulations, use a namelist from a UEnv
#namelist_genv      =
#namelist_source    =

