[DEFAULT]
# Default job configuration (all jobs)
# ------------------------------------
# Single-node:
partition          = shared
mem                = 20G
# Default binding in s2m
nnodes             = 1
ntasks             = 80

[escroc]
# Allow for climground / PREP generation
climground         = True
# Default ensemble members from 1 to 36
nmembers           = 35
subensemble        = E2
# Default GEnv
uenv               = uenv:s2m_escroc_testcase@vernaym
namelist_source    = OPTIONS_default.nam
#
# Default FORCING files (ESM-SnowMIP in Col de Porte)
forcing_xpid       = obs
forcing_user       = lafaysse
forcing_block      = meteo
forcing_vapp       = ESM-SnowMIP
forcing_vconf      = cdp
forcing_vortex1    = True
# Default PREP file
prep_vapp          = s2m
prep_vconf         = cdp
prep_xpid          = spinup
prep_user          = lafaysse
prep_date          = 2014100100
prep_vortex1       = True
# The ESM-SnowMIP FORCING file cover the entire simulation period
# change io_duration to 'yearly' if necessary in your use case
io_duration        = full

[inittg]

[prep]

[pgd]

[escroc_task]

[preprocess]
# Absolute path to local namelist
# WARNING : simulation reproductibility is not guaranteed
#namelist_path      =
# For reproductible simulations, use a namelist from a UEnv
#namelist_genv      =
#namelist_source    =

