###################################
# Template for an ESCROC simulation
###################################
# Context:
# ESCROC simulation with generation of initial conditions.
# Forcing from reanalysis.
#
# Launch command:
# mkjob -c .../vortex_cen/Crocus/escroc/conf/template_escroc_reanalysis.ini
#       -f .../vortex_cen/Crocus/escroc/jobs/escroc.job

[DEFAULT]
# Common configuration for all tasks

# HPC configuration (ASK BEFORE CHANGE)
partition          = normal256
nnodes             = 1
# Max number of members in parallel. Default set to 40 to avoid memory issues.
ntasks             = 38

# Maximum time for simulation HH:MM:SS (Be parsimonious)
time               = 1:00:00

# Env
uenv               = uenv:ref_cen.02@fructusm
gvar               = NAMELIST_V9_OPER
namelist_source    = OPTIONS_V9_OPER.nam

# FORCING files
forcing_user       = vernaym
forcing_vapp       = s2m
forcing_vconf      = reanalysis
forcing_xpid       = release_2026
forcing_block      = addslopes
# These elements the path on Hendrix where you placed the FORCING file:
# /home/forcing_user/vortex/forcing_vapp/forcing_vconf/forcing_xpid/forcing_block/FORCING.geometry_datebegin_dateend.nc

# Other: eXPerienceID and geometry of simulation
xpid               = template_escroc_E2
geometry           = cor2_allslopes

# Dates specification (if not specified in launching command line)
datebegin          = 2022-08-01 06
dateend            = 2022-12-31 06


[inittg]
# init_tg calculated from forcing
climground         = True

[prep]
# prep was calculated
tg_block           = init_tg

[pgd]
# got pgd from uenv

[escroc_task]
# Configuration of the ESCROC ensemble
nmembers           = 35
subensemble        = E2
