################################################
# Template for an ESCROC simulation on one point
################################################
# Context:
# PREP.nc, PGD.nc are assumed to be available (spinup already done)
# Run of SURFEX
#
# Launch command:
# mkjob -c .../vortex_cen/Crocus/escroc/conf/template_escroc_cdp.ini
#       -f .../vortex_cen/Crocus/escroc/jobs/escroc.job

[DEFAULT]
# Common configuration for all tasks

# HPC configuration (ASK BEFORE CHANGE)
partition          = normal256
nnodes             = 1
# Max number of members in parallel. Default set to 40 to avoid memory issues.
ntasks             = 38

# Maximum time for simulation HH:MM:SS (Be parsimonious)
time               = 0:20:00

# Env
uenv               = uenv:ref_cen.02@fructusm
namelist_source    = OPTIONS_V9_reanalysis.nam

# Do not allow for climground (a prep is given)
climground         = False

# Default ensemble members from 1 to 36
nmembers           = 35
subensemble        = E2

# Input files taken from Hendrix
# FORCING files (ESM-SnowMIP in Col de Porte)
forcing_xpid       = obs
forcing_user       = lafaysse
forcing_block      = meteo
forcing_vapp       = ESM-SnowMIP
forcing_vconf      = cdp
forcing_vortex1    = True
# PREP file
prep_vapp          = s2m
prep_vconf         = cdp
prep_xpid          = spinup
prep_user          = lafaysse
prep_datevalidity  = 2014-10-01 00
prep_vortex1       = True
# PGD File
pgd_vapp           = s2m
pgd_vconf          = cdp
pgd_xpid           = spinup
pgd_user           = lafaysse
pgd_vortex1        = True

# The ESM-SnowMIP FORCING file cover the entire simulation period
# change io_duration to 'yearly' if necessary in your use case
io_duration        = full

# Other: eXPerienceID and geometry of simulation
xpid = template_escroc_cdp
geometry = cdp

# Dates (dates of the simulation as well as the forcing file)
datebegin = 1994-10-01 01
dateend = 2014-10-01

[inittg]

[prep]

[pgd]

[escroc_task]
