! Created by  on 26/10/2020.
MODULE MODN_INTERPOL_SAFRAN

    !! Author:
    !! Sabine Radanovics
USE MODD_INTERPOL_SAFRAN
IMPLICIT NONE

    NAMELIST /NAM_SWITCHES_INT/ LMULTIINPUT, LMULTIOUTPUT
    NAMELIST /NAM_FILENAMES_SINGLE_IN/ HFILEIN, HGRIDIN
    NAMELIST /NAM_FILENAMES_SINGLE_OUT/ HFILEOUT
    NAMELIST /NAM_MULTIIN_SETTING/ NNUMBER_INPUT_GRIDS
    NAMELIST /NAM_FILENAMES_MULTI_IN/ HFILESIN, HGRIDSIN

END MODULE MODN_INTERPOL_SAFRAN