! Created by  on 26/10/2020.
MODULE MODN_INTERPOL_SAFRAN
! Author:
! Sabine Radanovics
USE MODD_INTERPOL_SAFRAN
IMPLICIT NONE

    NAMELIST /NAM_SWITCHES_INT/ LMULTIINPUT, LMULTIOUTPUT
    NAMELIST /NAM_FILENAMES_SINGLE_IN/ HFILEIN
    NAMELIST /NAM_FILENAMES_SINGLE_OUT/ HFILEOUT, HGRIDIN
    NAMELIST /NAM_MULTIIN_SETTING/ NNUMBER_INPUT_FILES
    NAMELIST /NAM_MULTIOUT_SETTING/ NNUMBER_OUTPUT_GRIDS
    NAMELIST /NAM_FILENAMES_MULTI_IN/ HFILESIN
    NAMELIST /NAM_FILENAMES_MULTI_OUT/ HFILESOUT, HGRIDSIN
    NAMELIST /NAM_OTHER_STUFF/ LTIMECHUNK, NLONCHUNKSIZE, NLATCHUNKSIZE

END MODULE MODN_INTERPOL_SAFRAN