! Created by  on 26/10/2020.
MODULE MODN_INTERPOL_SAFRAN

    !! Author:
    !! Sabine Radanovics
USE MODD_INTERPOL_SAFRAN
IMPLICIT NONE

    NAMELIST /NAM_SWITCHES_INT/ LMULTIINPUT

END MODULE MODN_INTERPOL_SAFRAN