#R
#R Massif geometry for Nivology models
#R -----------------------------------
#R
[all_massifs]
info       = All french mountain areas
kind       = unstructured
area       = fra

[postes]
info        = geometry for operational chain S2M-postes
kind        = unstructured
area        = postes
list        = alp,pyr,cor
iganame     = postes
slopes      = False

[postes_2022]
info        = geometry for operational chain S2M-postes
kind        = unstructured
area        = postes
list        = alp27_flat,pyr24_flat,cor2_flat,vog3_flat,jur4_flat,mac11_flat
iganame     = postes
slopes      = False

[alp]
info       = Historic Alps operational massif geometry (23 massifs, flat and 8 aspects)
kind       = unstructured
area       = alp
nmassif    = 23
slopes     = False

[alp27_flat]
info       = New Alps massif geometry (27 massifs, flat terrain only)
kind       = unstructured
area       = alp27_flat
nmassif    = 27
slopes     = False

[alp27_allslopes]
info       = New Alps massif geometry (27 massifs, flat and 8 aspects with 2 slopes)
kind       = unstructured
area       = alp27_allslopes
nmassif    = 27
slopes     = True

[pyr]
info       = Historic Pyrenees operational massif geometry (23 massifs, flat and 8 aspects)
kind       = unstructured
area       = pyr
nmassif    = 23
slopes     = False

[pyr24_flat]
info       = New Pyrenees operational massif geometry (24 massifs, flat terrain only)
kind       = unstructured
area       = pyr24_flat
nmassif    = 24
slopes     = False

[pyr24_allslopes]
info       = New Pyrenees operational massif geometry (24 massifs, flat and 8 aspects with 2 slopes)
kind       = unstructured
area       = pyr24_allslopes
nmassif    = 24
slopes     = True

[cor]
info       = Corsica operational massif geometry (2 massifs, flat and 8 aspects)
kind       = unstructured
area       = cor
nmassif    = 2
slopes     = False

[cor2_flat]
info       = Corsica operational massif geometry (2 massifs, flat terrain only)
kind       = unstructured
area       = cor2_flat
nmassif    = 2
slopes     = False

[cor2_allslopes]
info       = Corsica operational massif geometry (2 massifs, flat and 8 aspects with 2 slopes)
kind       = unstructured
area       = cor2_allslopes
nmassif    = 2
slopes     = True

[mac]
info       = Historic Massif Central operational massif geometry (3 massifs, flat terrain only)
kind       = unstructured
area       = mac
nmassif    = 11
slopes     = False

[mac11_flat]
info       = Massif-Central operational massif geometry (11 massifs, flat terrain only)
kind       = unstructured
area       = mac11_flat
nmassif    = 11
slopes     = False

[mac11_allslopes]
info       = Massif-Central operational massif geometry (11 massifs, flat and 8 aspects with 2 slopes)
kind       = unstructured
area       = mac11_allslopes
nmassif    = 11
slopes     = True

[vog]
info       = Historic Voges operational massif geometry (3 massifs, flat and X aspects)
kind       = unstructured
area       = vog
nmassif    = 3
slopes     = False

[vog3_flat]
info       = Vosges operational massif geometry (3 massifs, flat terrain only)
kind       = unstructured
area       = vog3_flat
nmassif    = 3
slopes     = False

[vog3_allslopes]
info       = Vosges operational massif geometry (3 massifs, flat and 8 aspects with 2 slopes)
kind       = unstructured
area       = vog3_allslopes
nmassif    = 3
slopes     = True

[jur]
info       = Historic Jura operational massif geometry (4 massifs, flat terrain only)
kind       = unstructured
area       = jur
nmassif    = 4
slopes     = False

[jur4_flat]
info       = Jura operational massif geometry (4 massifs, flat terrain only)
kind       = unstructured
area       = jur4_flat
nmassif    = 4
slopes     = False

[jur4_allslopes]
info       = Jura operational massif geometry (4 massifs, flat and 8 aspects with 2 slopes)
kind       = unstructured
area       = jur4_allslopes
nmassif    = 4
slopes     = True

[prosnow]
info       = Prosnow massif geometry (flat and 8 aspects)
kind       = unstructured
area       = prosnow

[alp_allslopes]
info       = Alps massif geometry with 0, 20, 40 degree slopes
kind       = unstructured
area       = alp_allslopes
iganame    = alp
nmassif    = 23
slopes     = True

[pyr_allslopes]
info       = Pyrenees massif geometry with 0, 20, 40 degree slopes
kind       = unstructured
area       = pyr_allslopes
iganame    = pyr
nmassif    = 23
slopes     = True

[cor_allslopes]
info       = Corse massif geometry with 0, 20, 40 degree slopes
kind       = unstructured
area       = cor_allslopes
iganame    = cor
nmassif    = 2
slopes     = True

[alp_flat]
info       = Alps massif geometry (flat)
kind       = unstructured
area       = alp_flat
nmassif    = 23
slopes     = False

[pyr_flat]
info       = Pyrenees massif geometry (flat)
kind       = unstructured
area       = pyr_flat
nmassif    = 23
slopes     = False

[cor_flat]
info       = Corse massif geometry with (flat)
kind       = unstructured
area       = cor_flat
nmassif    = 2
slopes     = False

[cdp]
info       = Col de Porte
kind       = unstructured
area       = cdp

[wfj]
info       = Weissflujoch
kind       = unstructured
area       = wfj

[rme]
info       = Reynolds Mountain East
kind       = unstructured
area       = rme

[sap]
info       = Sapporo
kind       = unstructured
area       = sap

[snb]
info       = Senator Beck
kind       = unstructured
area       = snb

[sod]
info       = Sodankyla
kind       = unstructured
area       = sod

[swa]
info       = Swap Angel
kind       = unstructured
area       = swa

[oas]
info       = Single point within a massif
kind       = unstructured
area       = oas

[obs]
info       = Single point within a massif
kind       = unstructured
area       = obs

[ojp]
info       = Single point within a massif
kind       = unstructured
area       = ojp

[Lautaret]
info       = Single point
kind       = unstructured
area       = lautaret

#R
#R Gridded geometry for EDELWEISS
#R ------------------------------
#R

[GrandesRousses1km]
info       = 1 km lat/lon regular grid
kind       = lonlat
area       = GrandesRousses1km
resolution = 0.01
lon0       = 5.81
lat0       = 44.79
nlon       = 89
nlat       = 66

[eaudolle1km]
info       = 1 km lat/lon regular grid
kind       = projected
area       = eaudolle1km
resolution = 0.01
lon0       = 5.61
lat0       = 44.59
nlon       = 150
nlat       = 106

[GrandesRousses250m]
info       = 250 m lat/lon regular grid
kind       = lonlat
area       = GrandesRousses250m
resolution = 0.250
runit      = km

[GrandesRousses_FRANXL0025]
info       = lat/lon FRANXL0025 BDAP regular grid over the Grandes Rousses domain
kind       = lonlat
area       = GrandesRousses

[GrandesRousses_EURW1S40]
info       = lat/lon EURW1S40 BDAP regular grid over the Grandes Rousses domain
kind       = lonlat
area       = GrandesRousses

[Alp1km]
info       = 250 m lat/lon regular grid
kind       = lonlat
area       = Alp1km

[Lautaret250m]
info       = Pleiades observations 2018
kind       = lonlat
area       = Lautaret250m

[Huez250m]
info       = Pleiades observations 2019 and 2020
kind       = lonlat
area       = Huez250m

[France25m]
info       = Digital Elevation Model over France at 25m resolution
kind       = lonlat
area       = France25m

[GrandesRousses25m]
info       = Digital Elevation Model over France at 25m resolution
kind       = projected
area       = France25m

#
# Unittest-specific geometries
# ----------------------------
#
[CintoRoto_1200m-1500m]
info       = Elevations 1200m and 1500m of the Cinto-Roto massif (massif 40)
kind       = Unstructured
area       = CintoRoto_1200m-1500m

################################################################
#                 USER-SPECIFIC GEOMETRIES			 #
################################################################

#
# Ange's geometries
# -----------------
#

[gr250ls]
info = geometrie du cas test SnowPappus et du papier TC, les vents de louis et l`interpolation lineaire de Safran (uniformisation du domaine a grandesrousses uniquement) avec la correction de hauteur de UREF dans les forcages.
kind = projected
resolution = 0.250
area = gr250ls
runit = km

[grandesroussesfull30louissafran]
info = Domaine Grandes Rousses a 30 m de resolution
kind = projected
resolution = 0.030
area = grandesroussesfull30louissafran
runit = km

[fullalpes]
info = zone retangulaire de 250m resoltion comprenant l`ensemble des massif des alpes francais
kind = projected
resolution = 0.250
area = fullalpes
runit = km
